### ISSUE TITLE
[Discussion] Identify a dataset with missing values for analysis

### ISSUE THREAD

**Issue by sver96** [sver96/ds-group-42-pba-3#1]
The first step of this assignment is to identify a publicly available dataset that has been investigated for missing values previously.
Recommendation is to start looking on [Kaggle](https://www.kaggle.com/) for an interesting dataset.

**Comment by sver96** [comment]
Potential candidates that I have found so far:
- https://www.kaggle.com/datasets/uciml/electric-power-consumption-data-set
- https://www.kaggle.com/datasets/arslanali4343/real-estate-dataset
- https://www.kaggle.com/datasets/devsubhash/flipkart-mobiles-dataset
- https://www.kaggle.com/datasets/akshayksingh/kidney-disease-dataset

**Comment by L1Z3M** [comment]
I removed the car price and rainfall from the possible datasets and left data set 2, which is salary predictions (classification problem). I also uploaded my data exploration as a JSON file for this dataset.

**Comment by L1Z3M** [comment]
> Potential candidates that I have found so far:
> 
> * https://www.kaggle.com/datasets/uciml/electric-power-consumption-data-set
> * https://www.kaggle.com/datasets/arslanali4343/real-estate-dataset
> * https://www.kaggle.com/datasets/devsubhash/flipkart-mobiles-dataset
> * https://www.kaggle.com/datasets/akshayksingh/kidney-disease-dataset

Sarel, Unfortunately, your first to third options look like they are designed for regression tasks. So I suggest we look at your last dataset. I will try to do some initial exploration during the day and then we have two possible candidates for tomorrow's meeting.

**Comment by L1Z3M** [comment]
I updated the data exploration JSON file and copied that along with Sarel's kidney disease dataset into the repository.

**Comment by Isa-dw** [comment]
On the assignment brief it stated that we should relate our findings to previous research that had used the same datasets.

<img width="742" alt="image" src="https://github.com/sver96/ds-group-42-pba-3/assets/138577940/5ec5df89-3ebc-41fd-a2cb-55763176bf87">

_I have identified the following papers that focused on missing value imputation:_
1. https://link-springer-com.ez.sun.ac.za/article/10.1007/s13042-022-01577-9#Fn3
2. https://iopscience.iop.org/article/10.1088/1755-1315/243/1/012111/pdf
3. https://www-sciencedirect-com.ez.sun.ac.za/science/article/pii/S003132030800201X?via%3Dihub#bib41

_Here are some of the datasets mentioned in these articles:_
**Article 1:**
- https://archive.ics.uci.edu/dataset/19/car+evaluation
- https://archive.ics.uci.edu/dataset/76/nursery
- https://archive.ics.uci.edu/dataset/224/gas+sensor+array+drift+dataset

**Article 2:**
- https://archive.ics.uci.edu/dataset/53/iris

**Article 3:**
- The 'car evaluation' and 'nursery' datasets from article 1 was also used in this article
- https://archive.ics.uci.edu/dataset/12/balance+scale

The third article is interesting, as it takes any data set from the repository ind induces missing data into it. not a bad idea. We can choose the 'cleanest' dataset, and then randomly induce missing values. then we are sure the difference in model performance is due to the quality of the data imputation and not due to some other data quality issues.

**Comment by sver96** [comment]
Team to review papers and datasets tonight/tomorrow to make a decision tomorrow on which to use.

**Comment by sver96** [comment]
We've decided to use the Nursery dataset and Springer / Sciencedirect paper.
